modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "yourender"
version = "${version}"
displayName = "YourEnder"
authors = "Kall"
description = '''
'''
#logoFile = ""

[[dependencies.yourender]]
modId="duplicationless"
mandatory=true
versionRange="[1.0.5,)"
ordering="NONE"
side="BOTH"